# Generated by Django 2.2.19 on 2023-04-22 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingrids_for_recipe',
        ),
        migrations.RenameModel(
            old_name='Ingridient',
            new_name='Ingredient',
        ),
        migrations.DeleteModel(
            name='IngridRecipe',
        ),
        migrations.AddField(
            model_name='ingredrecipe',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.Ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AddField(
            model_name='ingredrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.Recipe', verbose_name='Рецепт'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingreds_for_recipe',
            field=models.ManyToManyField(through='recipes.IngredRecipe', to='recipes.Ingredient', verbose_name='Ингридиенты'),
        ),
        migrations.AddConstraint(
            model_name='ingredrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredients'), name='Неравные ингридиенты'),
        ),
    ]
