# Generated by Django 3.2.18 on 2023-04-27 19:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0007_auto_20230427_2128"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredrecipe",
            old_name="quantity",
            new_name="amount",
        ),
    ]
