# Generated by Django 3.2.18 on 2023-04-27 19:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0008_rename_quantity_ingredrecipe_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredrecipe",
            old_name="ingredients",
            new_name="ingredient",
        ),
    ]
