# Generated by Django 3.2.18 on 2023-04-27 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0009_rename_ingredients_ingredrecipe_ingredient"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ingredrecipe",
            name="Неравные ингридиенты",
        ),
        migrations.AlterField(
            model_name="ingredrecipe",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient",
                to="recipes.ingredient",
                verbose_name="Ингредиенты",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredrecipe",
            constraint=models.UniqueConstraint(
                fields=("recipe", "ingredient"), name="Неравные ингридиенты"
            ),
        ),
    ]
