# Generated by Django 3.2.18 on 2023-04-29 08:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0011_alter_ingredrecipe_recipe"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="ingreds_for_recipe",
            new_name="ingredients",
        ),
    ]
