# Generated by Django 3.2.18 on 2023-04-29 18:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0012_rename_ingreds_for_recipe_recipe_ingredients"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="measurment_unit",
            new_name="measurement_unit",
        ),
    ]
