# Generated by Django 3.2.18 on 2023-04-29 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0014_alter_ingredrecipe_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredrecipe",
            name="amount",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Количество",
            ),
        ),
    ]
