# Generated by Django 3.2.18 on 2023-04-29 21:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0015_alter_ingredrecipe_amount"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="shoppinglist",
            name="Неравные списки",
        ),
    ]
